CREATE DATABASE Score;

USE Score;

CREATE TABLE score (
    id INT AUTO_INCREMENT PRIMARY KEY,
    tiempo INT NOT NULL,
    puntos INT NOT NULL,
    fecha DATETIME DEFAULT CURRENT_TIMESTAMP,
    nombre VARCHAR(255) NOT NULL
);
